package drools.spring.rules;

import drools.spring.example.facts.Symptom;
import drools.spring.example.facts.Illness;
import drools.spring.example.facts.Diagnose;

global Long pId;

rule "Patient sufferes from hypertension more than 6 months"
	salience 50
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
	when
		$illness: Illness( name == "Hronicna bubrezna bolest" && $numOfSymptoms: symptomsFound &&
			$numOfSpecSymptoms: specificSymptomsFound && $sym: symptomTermsFound )
		$s: Symptom( Symptom.Term.SUFFERS_FROM_HYPERTENSION_FOR_AT_LEAST_6_MONTHS not memberOf $sym )
		$d: Diagnose( $date: date && illnessName == "Hipertenzija" && patientId == pId && $date > (addMonths(6)) )
	then
	$illness.setSymptomsFound($numOfSymptoms + 1);
	$illness.setSpecificSymptomsFound($numOfSpecSymptoms + 1);
	$illness.getSymptomTermsFound().add(Symptom.Term.SUFFERS_FROM_HYPERTENSION_FOR_AT_LEAST_6_MONTHS);
	update($illness);
	
end

rule "Patient sufferes from Diabetes"
	salience 50
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
	when
		$d: Diagnose( illnessName ==  "Dijabetes" && patientId == pId )
		$illness: Illness( name == "Hronicna bubrezna bolest" && $numOfSymptoms: symptomsFound &&
			$numOfSpecSymptoms: specificSymptomsFound && $sym: symptomTermsFound )
		$s: Symptom( Symptom.Term.SUFFERS_FROM_DIABETES not memberOf $sym )
	then
		$illness.setSymptomsFound($numOfSymptoms + 1);
		$illness.setSpecificSymptomsFound($numOfSpecSymptoms + 1);
		$illness.getSymptomTermsFound().add(Symptom.Term.SUFFERS_FROM_DIABETES);
		update($illness);
end