package drools.spring.rules;

import drools.spring.example.facts.Disease;
import drools.spring.exampla.facts.Symptom;

rule "set num of symptom for disease prehlada"
	salience 50
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Prehlada", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "set num of symptom for disease groznica"
	salience 50
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Groznica", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "set num of symptom for disease upala krajnika"
	salience 50
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Upala krajnika", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "set num of symptom for disease sinusna infekcija"
	salience 50
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Sinusna infekcija", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "set num of symptom for disease hipertenzija"
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Hipertenzija", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "set num of symptom for disease dijabetes"
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Dijabetes", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "set num of symptom for disease hronicna bubrezna bolest"
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Hronicna bubrezna bolest", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "set num of symptom for disease akutna bubrezna povreda"
	agenda-group "set-symptom-num"
	no-loop 
	lock-on-active true
    when
        $d: Disease(title == "Akutna bubrezna povreda", $numSymptoms: numOfSymptoms, $numSpecificFound: specificSymptomFound)
        $s: Symptom ( isSpecific == true )
    then
    	$d.setNumOfSymptoms($numSymptoms + 1);
    	$d.setSpecificSymptomFound($numSpecificFound + 1);
    	update($d);
end

rule "nonspecific symptoms"
	salience 100
	agenda-group "set-symptom-num"
	lock-on-active true
	when
		$d : Disease( $sym: symptoms)
		$list: List() from collect(Symptom())
		$resList: List(size > 0) from accumulate(
		$s: Symptom( isSpecific memberOf $sym, isSpecific == false)
		from $list, 
		init(int count = 0;)),
		action(count++;),
		result(count)
	then 
		$d.setNumOfSymptoms($numSymptoms + count);
		update($d);
end